name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Run tests
      run: python -m pytest -v tests/test.py

    - name: Build docker
      run: |
        if [ "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" = "master" ]; then
          TAG="latest"
        else
          TAG="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        fi
        docker build -f app/Dockerfile -t test:$TAG .
